# -*- coding: utf-8 -*-
"""brain-lox.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nMNic3dfINjYvrc1LriiK1UN_Sz7Hn3J
"""

import requests

url = 'https://brainlox.com/courses/category/technical'
response = requests.get(url)
html_content = response.text

from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
model = AutoModel.from_pretrained('bert-base-uncased')

text = "Learn Scratch Programming"
inputs = tokenizer(text, return_tensors='pt')
embeddings = model(**inputs).last_hidden_state

!pip install flask_restful

from flask import Flask, request
from flask_restful import Resource, Api

app = Flask(__name__)
api = Api(app)

class Conversation(Resource):
    def get(self):
        # Handle the conversation here
        pass

api.add_resource(Conversation, '/conversation')

if __name__ == '__main__':
    app.run(debug=True)